## Global Historical Climatology Network Dataset
Variables are stored in both rows and columns
This dataset represents the daily weather records for a weather station (MX17004) in Mexico for five months in 2010.

In [177]:
import pandas as pd
df = pd.read_csv('../weather-raw.csv')
display(df)

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,26.4,NaN,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,15.0,NaN,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
print('Nº Null:\n',df.isnull().sum())

Nº Null:
 id          0
year        0
month       0
element     0
d1         20
d2         18
d3         18
d4         20
d5         14
d6         20
d7         20
d8         20
d9         22
d10        20
d11        20
d12        22
d13        20
d14        18
d15        20
d16        20
d17        20
d18        22
d19        22
d20        22
d21        22
d22        22
d23        18
d24        22
d25        20
d26        20
d27        16
d28        20
d29        18
d30        20
d31        20
dtype: int64

In [179]:
'''
Elimino las columnas que no tienen datos por lo que las considero columnas erroneas
'''

df= df[['id', 'year', 'month', 'element', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6',
       'd7', 'd8', 'd10', 'd11', 'd13', 'd14', 'd15', 'd16',
       'd17', 'd23', 'd25', 'd26',
       'd27', 'd28', 'd29', 'd30', 'd31']]
display(df)

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d16,d17,d23,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,31.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,17.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,28.0,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17.5,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,NaN,26.4,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,NaN,15.0,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [180]:
df = df.fillna(0)
#display(df)
variable = df[['id','year','month', 'element']]

In [181]:
variable

         id  year  month element
0   MX17004  2010      1    tmax
1   MX17004  2010      1    tmin
2   MX17004  2010      2    tmax
3   MX17004  2010      2    tmin
4   MX17004  2010      3    tmax
5   MX17004  2010      3    tmin
6   MX17004  2010      4    tmax
7   MX17004  2010      4    tmin
8   MX17004  2010      5    tmax
9   MX17004  2010      5    tmin
10  MX17004  2010      6    tmax
11  MX17004  2010      6    tmin
12  MX17004  2010      7    tmax
13  MX17004  2010      7    tmin
14  MX17004  2010      8    tmax
15  MX17004  2010      8    tmin
16  MX17004  2010     10    tmax
17  MX17004  2010     10    tmin
18  MX17004  2010     11    tmax
19  MX17004  2010     11    tmin
20  MX17004  2010     12    tmax
21  MX17004  2010     12    tmin

In [182]:
Temperaturas  =df.drop(columns=['id','year','month', 'element'])

In [183]:
Temperaturas

,d1,d2,d3,d4,d5,d6,d7,d8,d10,d11,...,d16,d17,d23,d25,d26,d27,d28,d29,d30,d31
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.8,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.5,0.0
2,0.0,27.3,24.1,0.0,0.0,0.0,0.0,0.0,0.0,29.7,...,0.0,0.0,29.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,14.4,14.4,0.0,0.0,0.0,0.0,0.0,0.0,13.4,...,0.0,0.0,10.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,32.1,0.0,0.0,0.0,34.5,0.0,...,31.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,14.2,0.0,0.0,0.0,16.8,0.0,...,17.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,36.3,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,16.7,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,18.2,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,28.0,0.0,0.0,0.0,0.0,0.0,30.1,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,17.5,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0
12,0.0,0.0,28.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,17.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,29.6,0.0,0.0,29.0,0.0,0.0,...,0.0,0.0,26.4,29.7,0.0,0.0,0.0,28.0,0.0,25.4
15,0.0,0.0,0.0,0.0,15.8,0.0,0.0,17.3,0.0,0.0,...,0.0,0.0,15.0,15.6,0.0,0.0,0.0,15.3,0.0,15.4
16,0.0,0.0,0.0,0.0,27.0,0.0,28.1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,31.2,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,14.0,0.0,12.9,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0
18,0.0,31.3,0.0,27.2,26.3,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,28.1,27.7,0.0,0.0,0.0,0.0
19,0.0,16.3,0.0,12.0,7.9,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,12.1,14.2,0.0,0.0,0.0,0.0
20,29.9,0.0,0.0,0.0,0.0,27.8,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,13.8,0.0,0.0,0.0,0.0,10.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [188]:
temperatures_fina = []
for i in range(22):
    media = []
    for e in Temperaturas.iloc[i]:
        if e != 0:
            media.append(e)   
    temperatures_fina.append(sum(media)/len(media))

In [189]:
df_limpio = variable
df_limpio['Temp_Media_dias'] = temperatures_fina
display(df_limpio)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

         id  year  month element  Temp_Media_dias
0   MX17004  2010      1    tmax        27.800000
1   MX17004  2010      1    tmin        14.500000
2   MX17004  2010      2    tmax        27.750000
3   MX17004  2010      2    tmin        13.225000
4   MX17004  2010      3    tmax        32.566667
5   MX17004  2010      3    tmin        16.200000
6   MX17004  2010      4    tmax        36.300000
7   MX17004  2010      4    tmin        16.700000
8   MX17004  2010      5    tmax        33.200000
9   MX17004  2010      5    tmin        18.200000
10  MX17004  2010      6    tmax        29.050000
11  MX17004  2010      6    tmin        17.750000
12  MX17004  2010      7    tmax        29.250000
13  MX17004  2010      7    tmin        17.000000
14  MX17004  2010      8    tmax        28.271429
15  MX17004  2010      8    tmin        15.842857
16  MX17004  2010     10    tmax        28.900000
17  MX17004  2010     10    tmin        13.080000
18  MX17004  2010     11    tmax        28.120000
19  MX17004  2010     11    tmin        12.500000
20  MX17004  2010     12    tmax        28.850000
21  MX17004  2010     12    tmin        12.150000